# fly.toml app configuration file for server-delicate-mountain-4709
# See https://fly.io/docs/reference/configuration/

app = 'server-delicate-mountain-4709'
primary_region = 'waw'

[build]
  # Dockerfile istifadə olunacaq

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app'] # Aşağıdakı [processes] içindəki 'app'-i işə sal

# ----- BAŞLATMA ƏMRİNİ DƏQİQ GÖSTƏRİRİK -----
[processes]
  app = "node server/server_multi.js" # Fayl server qovluğunda olduğu üçün
# -----------------------------------------

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1