# fly.toml app configuration file generated for kingzone on 2025-04-15T00:00:00+04:00
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'kingzone' # <<<--- Tətbiq adınızın düzgün olduğundan əmin olun
primary_region = 'waw' # <<<--- Sizin regionunuz

[build]
  # Dockerfile istifadə olunursa, buranı boş saxlaya və ya Dockerfile ayarlarını əlavə edə bilərsiniz
  # Əgər @flydotio/dockerfile istifadə edirsinizsə, bura aid ayarlar ola bilər

# Əsas prosesi təyin edirik - server.js işə düşməlidir
[processes]
  app = "node server/server.js"

# Servislər və portlar
[[services]]
  internal_port = 8080 # Node.js tətbiqinizin dinlədiyi port (PORT mühit dəyişəni və ya default 8080)
  processes = ["app"] # Yuxarıdakı 'app' prosesini istifadə edir
  protocol = "tcp"
  auto_stop_machines = true # İstifadədə olmadıqda maşınları dayandır
  auto_start_machines = true # Sorğu gəldikdə maşınları başlat
  min_machines_running = 0 # Aktiv maşın sayını 0-a endirə bilər

  # HTTP portu (80)
  [[services.ports]]
    handlers = ["http"]
    port = 80
    force_https = true # Avtomatik HTTPS-ə yönləndir

  # HTTPS portu (443)
  [[services.ports]]
    handlers = ["tls", "http"] # TLS (SSL) və HTTP trafikini qəbul edir
    port = 443

  # Sağlamlıq yoxlaması (TCP Check - daha sadə)
  # Fly.io tətbiqin işlək olub olmadığını yoxlamaq üçün internal_port-a qoşulmağa çalışacaq
  [[services.tcp_checks]]
    interval = "15s"      # Yoxlamalar arası 15 saniyə
    timeout = "2s"        # Qoşulma üçün 2 saniyə vaxt
    grace_period = "10s"  # Tətbiq başladıqdan sonra ilk yoxlamadan əvvəl 10 saniyə gözləmə (bu vacibdir!)
    # restart_limit = 0   # Yoxlama uğursuz olsa Fly.io özü idarə edir

# Virtual Maşın ölçüsü (əvvəlki kimi)
[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1